### ISSUE TITLE
Not working in nuxt 3

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [bestkolobok/nuxt-jsoneditor#2]

**Comment by bestkolobok** [comment]
Please describe your problem. What exactly is not working? What errors are you seeing in the console? 
Because this module was created specifically for Nuxt3.

Just checked that the module works for Nuxt 3.0.0-rc.6 and 3.0.0-rc.8

You may have this problem after updating Nuxt version. The README describes what to do in this case:
"If you have problems starting Nuxt after updating this package, try removing yarn.lock and node_modules folder, then reinstall dependencies yarn install. If that doesn't help, update the Nuxt and @pinia/nuxt packages"
